sudo: false
language: node_js
node_js:
  - 0.12
  - 4
  - 5
addons:
  firefox: latest
  postgresql: 9.4
install:
  - npm install
  - npm install bitcore-lib
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp test/config/postgresql.json.travis test/config/postgresql.json
  - sh -e /etc/init.d/xvfb start
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TEST_SUITE=test
matrix:
  include:
    - node_js: 4
      env: TEST_SUITE=coverage
    - node_js: 4
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
