language: node_js
node_js:
  - "0.10"
addons:
  firefox: "38.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
env:
  - TEST_SUITE=build
  - TEST_SUITE=coveralls
  - TEST_SUITE=lint
  - TEST_SUITE=test
script: "npm run $TEST_SUITE"
